[workspace]
authors = ["Javern Goh <javerngoh@gmail.com>"]
channels = ["conda-forge"]
name = "am93nYOWl400BMxhyHyWhM"
platforms = ["win-64"]
version = "0.0.0"

[tasks]

[dependencies]

[feature.dev.dependencies]
gh = "*"

[environments.dev]
features = ["dev"]
solve-group = "default"